// <auto-generated />
using System;
using ASMCshrp4_12345.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASMCshrp4_12345.Migrations
{
    [DbContext(typeof(Csharp4Context))]
    [Migration("20241030160740_createDatabase")]
    partial class createDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASMCshrp4_12345.Models.Chatlieu", b =>
                {
                    b.Property<string>("MaChatLieu")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TenChatLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChatLieu");

                    b.ToTable("Chatlieus");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Chitiethoadon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaSp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuongMua")
                        .HasColumnType("int");

                    b.HasKey("MaHoaDon", "MaSp");

                    b.HasIndex("MaSp");

                    b.ToTable("Chitiethoadons");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Chitietphieunhap", b =>
                {
                    b.Property<string>("MaCtpn")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<double>("DonGiaNhap")
                        .HasColumnType("float");

                    b.Property<string>("MaPhieuNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<int>("SoluongNhap")
                        .HasColumnType("int");

                    b.HasKey("MaCtpn");

                    b.HasIndex("MaPhieuNhap");

                    b.HasIndex("MaSp");

                    b.ToTable("Chitietphieunhaps");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Hinhanh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("HinhAnh1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSp")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaSp");

                    b.ToTable("Hinhanhs");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Hoadon", b =>
                {
                    b.Property<string>("MaHoaDon")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DiaChiNhanHang")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Hoten")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Httt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaNv")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgayTao")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateOnly>("ThoiGianDat")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ThoiGianGiao")
                        .HasColumnType("date");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaHoaDon");

                    b.HasIndex("MaKh");

                    b.HasIndex("MaNv");

                    b.ToTable("Hoadons");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Khachhang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Cccd")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaKh");

                    b.ToTable("Khachhangs");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Kichthuoc", b =>
                {
                    b.Property<string>("MaKichThuoc")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("KichThuoc1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKichThuoc")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MaKichThuoc");

                    b.ToTable("Kichthuocs");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Mausac", b =>
                {
                    b.Property<string>("MaMau")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TenMau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaMau");

                    b.ToTable("Mausacs");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Nhacungcap", b =>
                {
                    b.Property<string>("MaNhaCc")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenNhaCc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaNhaCc");

                    b.ToTable("Nhacungcaps");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Nhanvien", b =>
                {
                    b.Property<string>("MaNv")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Cccd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<int>("Luong")
                        .HasColumnType("int");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayVaoLam")
                        .HasColumnType("date");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("TinhTrang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNv");

                    b.ToTable("Nhanviens");

                    b.HasData(
                        new
                        {
                            MaNv = "NV001",
                            Cccd = "123456789",
                            DiaChi = "BMT",
                            Email = "thanhdat0968367@gmail.com",
                            GioiTinh = "Nam",
                            HoTen = "Admin",
                            IsDelete = false,
                            Luong = 10000000,
                            MatKhau = "Admin123",
                            NgaySinh = new DateOnly(2005, 2, 23),
                            NgayVaoLam = new DateOnly(2023, 1, 1),
                            Sdt = "0123456789",
                            TenTaiKhoan = "Admin",
                            TinhTrang = "Hoạt động",
                            VaiTro = "Admin"
                        });
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Phieunhap", b =>
                {
                    b.Property<string>("MaPhieuNhap")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateOnly>("ThoiGianNhap")
                        .HasColumnType("date");

                    b.HasKey("MaPhieuNhap");

                    b.ToTable("Phieunhaps");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Sanpham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<double>("DonGiaBan")
                        .HasColumnType("float");

                    b.Property<string>("Hinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("MaChatLieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaKichThuoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaMau")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaNhaCc")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MaThuongHieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("NgaySanXuat")
                        .HasColumnType("date");

                    b.Property<int>("SoLuongBan")
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaSp");

                    b.HasIndex("MaChatLieu");

                    b.HasIndex("MaKichThuoc");

                    b.HasIndex("MaMau");

                    b.HasIndex("MaNhaCc");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("Sanphams");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Thuonghieu", b =>
                {
                    b.Property<string>("MaThuongHieu")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("bit");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaThuongHieu");

                    b.ToTable("Thuonghieus");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Chitiethoadon", b =>
                {
                    b.HasOne("ASMCshrp4_12345.Models.Hoadon", "MaHoaDonNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASMCshrp4_12345.Models.Sanpham", "MaSpNavigation")
                        .WithMany("Chitiethoadons")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaHoaDonNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Chitietphieunhap", b =>
                {
                    b.HasOne("ASMCshrp4_12345.Models.Phieunhap", "MaPhieuNhapNavigation")
                        .WithMany("Chitietphieunhaps")
                        .HasForeignKey("MaPhieuNhap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASMCshrp4_12345.Models.Sanpham", "MaSpNavigation")
                        .WithMany("Chitietphieunhaps")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaPhieuNhapNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Hinhanh", b =>
                {
                    b.HasOne("ASMCshrp4_12345.Models.Sanpham", "MaSpNavigation")
                        .WithMany("Hinhanhs")
                        .HasForeignKey("MaSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Hoadon", b =>
                {
                    b.HasOne("ASMCshrp4_12345.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaKh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASMCshrp4_12345.Models.Nhanvien", "MaNvNavigation")
                        .WithMany("Hoadons")
                        .HasForeignKey("MaNv");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("MaNvNavigation");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Sanpham", b =>
                {
                    b.HasOne("ASMCshrp4_12345.Models.Chatlieu", "MaChatLieuNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaChatLieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASMCshrp4_12345.Models.Kichthuoc", "MaKichThuocNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaKichThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASMCshrp4_12345.Models.Mausac", "MaMauNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaMau")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASMCshrp4_12345.Models.Nhacungcap", "MaNhaCcNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaNhaCc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASMCshrp4_12345.Models.Thuonghieu", "MaThuongHieuNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaThuongHieu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaChatLieuNavigation");

                    b.Navigation("MaKichThuocNavigation");

                    b.Navigation("MaMauNavigation");

                    b.Navigation("MaNhaCcNavigation");

                    b.Navigation("MaThuongHieuNavigation");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Chatlieu", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Hoadon", b =>
                {
                    b.Navigation("Chitiethoadons");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Khachhang", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Kichthuoc", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Mausac", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Nhacungcap", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Nhanvien", b =>
                {
                    b.Navigation("Hoadons");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Phieunhap", b =>
                {
                    b.Navigation("Chitietphieunhaps");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Sanpham", b =>
                {
                    b.Navigation("Chitiethoadons");

                    b.Navigation("Chitietphieunhaps");

                    b.Navigation("Hinhanhs");
                });

            modelBuilder.Entity("ASMCshrp4_12345.Models.Thuonghieu", b =>
                {
                    b.Navigation("Sanphams");
                });
#pragma warning restore 612, 618
        }
    }
}
